version: '3.4'

services:
  mssql:
    container_name: sql-server-2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Sa@123"
      ACCEPT_EULA: "Y"
    volumes:
      - my-volume:/var/opt/mssql
    
volumes:
  my-volume:
