version: '3.4'

services:
  mssql:
    container_name: sql-server-2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - 1434:1433
    environment:
      MSSQL_SA_PASSWORD : "Sa@123456"
      ACCEPT_EULA: "Y"
    volumes:
      - my-volume:/var/opt/mssql
    
volumes:
  my-volume:
